; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f401ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
board_build.mcu = stm32f411ceu6
board_build.f_cpu = 96000000L

upload_protocol = stlink

monitor_port = COM10      ; change to your actual port
monitor_speed = 115200     ; match your DEBUGSERIAL.begin() baud rate
monitor_filters = direct

lib_deps = rock7/RockBLOCK-9704@^0.1.29

lib_ldf_mode = deep+
build_flags = 
    -DIMT_PAYLOAD_SIZE=512U
