[env:blackpill_f401ce]
platform = ststm32
board = blackpill_f401ce
framework = arduino

upload_protocol = cmsis-dap
debug_tool = cmsis-dap

; Optional but explicit:
board_build.mcu = stm32f401ceu6
board_build.f_cpu = 84000000L

lib_deps = rock7/RockBLOCK-9704@^0.1.29

debug_server =
    openocd
    -f interface/cmsis-dap.cfg
    -f target/stm32f4x.cfg

    upload_flags =
    -c "cmsis_dap_backend hid"